---
shell: "/bin/bash"

basic_apps:
  - sudo
  - vim
  - ufw
  - curl
  - wget

ports_open:
  - 22

users:
  - name: admin
    password: "admin2010"
    groups: sudo
    home: yes
  - name: ansible
    password: "ansible2010"
    groups: sudo
    home: yes
  - name: sam
    password: "2310"
    home: yes

keys:
  - name: sam
    key: "/mnt/n/server/keys/sam_id-rsa.pub"
  - name: admin
    key: "/mnt/n/server/keys/sam_id-rsa.pub"
  - name: ansible
    key: "/mnt/n/server/keys/ansible_id-rsa.pub"
