---
- name: Open TCP Ports
  ufw:
    rule: allow
    port: "{{ item }}"
    proto: tcp
  ignore_errors: true
  loop: "{{ ports_open_tcp }}"
  loop_control:
        loop_var: item

- name: Open UDP Ports
  ufw:
    rule: allow
    port: "{{ item }}"
    proto: udp
  ignore_errors: true
  loop: "{{ ports_open_udp }}"
  loop_control:
        loop_var: item

- name: Outgoing allow
  ufw:
    direction: outgoing
    policy: allow
  ignore_errors: true

- name: Incoming deny
  ufw:
    direction: incoming
    policy: deny
  ignore_errors: true

- name: Enable UFW
  ufw:
    state: enabled
  ignore_errors: true
