---
- name: Setup Hyperviser
  hosts: hyperviser
  become: true

  vars:
    ansible_user: "{{ connect_user }}"
    ansible_ssh_private_key_file: "/mnt/n/server/keys/ansible_id-rsa"

  roles:
    - role: simoncaron.pve_addons
      vars:
        pve_addons_remove_enterprise_repo: true
        pve_addons_add_no_subscription_repo: true
        pve_addons_remove_subscription_nag: true
    - role: os_debian-linux
