---
- name: Setup Hyperviser
  hosts: hyperviser
  become: true

  vars:
    ansible_user: "{{ connect_user }}"
    ansible_ssh_private_key_file: "/home/sam/.ssh/ansible_id-rsa"

  roles:
    - role: simoncaron.pve_addons
      vars:
        pve_addons_remove_enterprise_repo: true
        pve_addons_add_no_subscription_repo: true
        pve_addons_remove_subscription_nag: true
    - role: os_debian-linux
    - role: copier

  tasks:
    - name: Give Admin User Proxmox Administrator Privileges
      shell: "pveum user add admin@pam && pveum acl modify / --roles Administrator --users admin@pam"
      ignore_errors: true
