---
- name: Switch Hyperviser Subnet
  hosts: hyperviser
  become: true

  vars:
    ansible_user: "{{ connect_user }}"
    ansible_ssh_private_key_file: "/home/sam/.ssh/ansible_id-rsa"

  roles:
    - role: change-network_debian-linux
